// Generated by Wrangler by running `wrangler types`

interface Env {
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_TRUSTED_ORIGINS: string;
	RESEND_API_KEY: string;
	RESEND_SENDER_EMAIL: string;
	R2_CLIENT_ID: string;
	R2_CLIENT_SECRET: string;
	DB: D1Database;
}
